name: Kibot

on:
  workflow_dispatch:
  push:
    paths:
      - "pcb/*.kicad_sch"
      - "pcb/*.kicad_pcb"
      - "pcb/*.kicad_pro"
      - "**/*kibot.yml"
  pull_request:
    paths:
      - "pcb/*.kicad_sch"
      - "pcb/*.kicad_pcb"
      - "pcb/*.kicad_pro"
      - "**/*kibot.yml"

env:
  schema: "pcb/*.kicad_sch"
  board: "pcb/*.kicad_pcb"
  dir: .

jobs:
  # checks
  ERC:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    steps:
      - uses: actions/checkout@v4
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s drc -v -i
  DRC:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    steps:
      - uses: actions/checkout@v4
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s erc -v -i
  # documentation
  docs:
    runs-on: ubuntu-latest
    needs: [ERC]
    container:
      image: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    steps:
      - uses: actions/checkout@v4
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s erc,drc -v \
            ibom.html schematic.pdf schematic.svg board_top.pdf board_bottom.pdf
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_docs
          if-no-files-found: error
          path: |
            ${{env.dir}}/docs/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log
  # fabrications
  gerbers:
    runs-on: ubuntu-latest
    needs: [DRC]
    container:
      image: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    steps:
      - uses: actions/checkout@v4
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s erc,drc -v \
            gerbers.gbr drills.gbr drills.drl pickandplace.csv bom.csv JLCPCB_gerbers JLCPCB_drill JLCPCB_position JLCPCB_bom JLCPCB PCBWay_gerbers PCBWay_drill PCBWay
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_gerbers
          if-no-files-found: error
          path: |
            ${{env.dir}}/gerbers/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log
  # cad
  cad:
    runs-on: ubuntu-latest
    needs: [DRC]
    container:
      image: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    steps:
      - uses: actions/checkout@v4
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s erc,drc -v \
            model.step
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_cad
          if-no-files-found: error
          path: |
            ${{env.dir}}/cad/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log
  # images
  render:
    runs-on: ubuntu-latest
    needs: [DRC]
    container:
      image: ghcr.io/inti-cmnb/kicad9_auto_full:latest
    steps:
      - uses: actions/checkout@v4
      - name: run kibot
        run: |
          kibot -c kibot.yml -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s erc,drc -v \
            board_black_top.svg board_black_bottom.svg enig_green_top.svg enig_green_bottom.svg enig_green_top.png enig_green_bottom.png
      - uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_img
          if-no-files-found: error
          path: |
            ${{env.dir}}/img/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log
  update-repo:
    runs-on: ubuntu-latest
    needs: [docs, gerbers, render]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "pcb-artifacts"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: arts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R arts

      - name: Extract and organize files
        run: |
          # Copy schematic PDF
          cp arts/modelk-schematic.* pcb/autogen/

          # Copy iBOM
          cp arts/bom/modelk-ibom.html pcb/autogen/ibom.html

          # Copy PCB renders
          cp arts/pcb/jlcpcb/green_enig/modelk-top.svg pcb/autogen/top.svg
          cp arts/pcb/jlcpcb/green_enig/modelk-bottom.svg pcb/autogen/bottom.svg
          cp arts/pcb/jlcpcb/green_enig/modelk-top.png pcb/autogen/top.png
          cp arts/pcb/jlcpcb/green_enig/modelk-bottom.png pcb/autogen/bottom.png

          # Copy JLCPCB zip
          cp arts/JLCPCB/modelk-JLCPCB.zip pcb/autogen/jlcpcb.zip

          # Copy PCBWay zip
          cp arts/PCBWay/modelk-PCBWay.zip pcb/autogen/pcbway.zip

      - uses: EndBug/add-and-commit@v9
        with:
          add: "pcb/autogen/ --force"
          default_author: github_actions
          message: "Update PCB artifacts from KiBot"
          new_branch: pcb-artifacts
          push: origin pcb-artifacts # force is probably fine, it's separate
